baseURL = "http://crfm.de/"
languageCode = "fr"
title = "Club de Rhétorique Francophone de Munich"
theme = "hugo-toast"

[params]
    name = "Club de Rhétorique Francophone de Munich (CFRM)"
    description = ""
    email = "contact@crfm.de"
    address = "EineWeltHaus München e.V. 80, Schwanthalerstraße, 80336 München, Germany"
    year = 2019
    logo = "images/toastmasters_blue.png"
	serviceTitle = "Rejoignez-nous!"
    background = ""
    favicon = "images/Favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
	showWhere = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false
	footerEnableMailChimpWidget = true

[[menu.main]]
    name = "accueil"
    url = "/"
    weight = 1

[[params.social]]
	title = "facebook"
	url = "https://facebook.com/100012379179587"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:contact@crfm.de"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"